### ISSUE TITLE
Global resource-specific metadata

### ISSUE THREAD

**Issue by quickstar** [json-api-dotnet/JsonApiDotNetCore#994]
#### DESCRIPTION
As of today, there are two ways to define metadata. Either global (once per response) or per resource (for each item in the result the metadata is added).

If we add the metadata per resource we can easily gather additional information about the entity by accessing the generic type information via reflection. Unfortunately this seems not possible if using the global metadata, because the interface is lacking the type information.

#### ACTUAL BEHAVIOR
Consider the following entity, which contains additional attributes which are used to generate meta data.
```c#
public sealed class SupportTicket : Identifiable
{
    [Attr]
    [Required]
    [MaxLength(200)]
    public string Description { get; set; }
}
```
The only way to include those metadata is by creating a ResourceDefinition inherit from ` JsonApiResourceDefinition<SupportTicket>` which then allows us to override `IDictionary<string, object> GetMeta(SupportTicket resource)`. This allows us to create something like this:

```yaml
{
    "links": {
        "self": "http://localhost/supportTickets",
        "first": "http://localhost/supportTickets"
    },
    "data": [
        {
            "type": "supportTickets",
            "id": "1",
            "attributes": {
                "description": "Critical: Quae magnam est modi quaerat voluptas repellendus quos dolorem. Ipsum rerum voluptatem facere. Veniam dolor soluta repudiandae doloribus. Qui ratione soluta velit deleniti atque id ad dicta sint."
            },
            "links": {
                "self": "http://localhost/supportTickets/1"
            },
            "meta": {
                "rules": [
                    "required": "true",
                    "maxLength": "200" 
                ]
            }
        }, {
            "type": "supportTickets",
            "id": "2",
            "attributes": {
                "description": "Lorem ipsum dolor sit....."
            },
            "links": {
                "self": "http://localhost/supportTickets/2"
            },
            "meta": {
                "rules": [
                    "required": "true",
                    "maxLength": "200" 
                ]
            }
        }
    ]
}
```

Even though this generally works, the data sent to the client is highly redundant.

#### EXPECTED BEHAVIOR
We need a way to create entity related global meta data which leads to the following result:

```yaml
{
    "links": {
        "self": "http://localhost/supportTickets",
        "first": "http://localhost/supportTickets",
        "meta": {
            "rules": [
                "required": "true",
                "maxLength": "200" 
            ]
        }
    },
    "data": [
        {
            "type": "supportTickets",
            "id": "1",
            "attributes": {
                "description": "Critical: Quae magnam est modi quaerat voluptas repellendus quos dolorem. Ipsum rerum voluptatem facere. Veniam dolor soluta repudiandae doloribus. Qui ratione soluta velit deleniti atque id ad dicta sint."
            },
            "links": {
                "self": "http://localhost/supportTickets/1"
            }
        }, {
            "type": "supportTickets",
            "id": "2",
            "attributes": {
                "description": "Lorem ipsum dolor sit....."
            },
            "links": {
                "self": "http://localhost/supportTickets/2"
            }
        }
    ]
}
```
